Register DEFAULT group on agent start
sapcc/asr1k-neutron-l3 pull request #116
Opened 2024-10-11 13:05 UTC by sven-rosenzweig

From upstream commit 4d3a2747 fixing bug (#1968606), registration of the group DEFAULT does not happen automatically anymore.

If not loaded, agent fails with 'oslo_config.cfg.NoSuchOptError: no such option api_extensions_path in group [DEFAULT]'

2024-11-11 14:22 UTC, sebageek approved these changes

2024-11-11 14:25 UTC, sebageek requested changes
Is the import correct?

2024-11-11 14:25 UTC, sebageek commented on asr1k_neutron_l3/plugins/l3/agents/asr1k_l3_agent.py
> +    common_config.register_core_common_config_opts()
Are you sure `common_config` is the right module? We import it as `from neutron.common import config as common_config` but the method is defined in `neutron.conf.common` (for stable/yoga).

2024-11-12 12:33 UTC, sven-rosenzweig commented on asr1k_neutron_l3/plugins/l3/agents/asr1k_l3_agent.py
> +    common_config.register_core_common_config_opts()
Yes, import is right (for stable/2024.1). (https://github.com/sapcc/neutron/blob/0aa154b5ce9dc8da73309fb212843a2b69b68696/neutron/common/config.py#L52). Fixing the [bug](https://bugs.launchpad.net/neutron/+bug/1968606) makes this necessary.

2024-11-12 13:50 UTC, sebageek commented on asr1k_neutron_l3/plugins/l3/agents/asr1k_l3_agent.py
> +    common_config.register_core_common_config_opts()
The commit you're referencing is not part of `stable/yoga-m3`. I can't find the method in the referenced file in `stable/yoga-m3`, meaning if we're going to merge it we're going to break the asr driver on yoga release - oooor I looked wrong and it's imported from somewhere? But if I'm right we need to either fix the import for yoga or we only fix this in Caracal, meaning you'd need to open this PR against `stable/2024.1-m3`.

2024-11-12 13:56 UTC, sven-rosenzweig commented on asr1k_neutron_l3/plugins/l3/agents/asr1k_l3_agent.py
> +    common_config.register_core_common_config_opts()
Thx for pointing me to this. I wanted to open the PR against `stable/2024.1-m3`.

2024-11-12 14:28 UTC, sebageek commented on asr1k_neutron_l3/plugins/l3/agents/asr1k_l3_agent.py
> +    common_config.register_core_common_config_opts()
As per our call let's use `register_common_config_options()` from `neutron.common.config`.

2024-11-12 15:41 UTC, sebageek approved these changes

2024-11-13 10:17 UTC, swagner-de approved these changes

2024-11-13 10:38 UTC, merged